### ISSUE TITLE
Version 1.5 not working on Mi 10 ultra

### ISSUE THREAD

**Issue by andrea-musci** [Xposed-Modules-Repo/com.qingyu.mi5g#2]
Hi, the latest version is not working on Mi 10 ultra with xiaomi.eu 13.0.5. Version 1.4 worked good. The new version does not change 5G status and opens synch settings on long click, instead of preferred network. Restored 1.4 and everything works again.
Thx

**Comment by buffcow** [comment]
Use the latest version 1.7
