### ISSUE TITLE
双卡切换通知栏状态不能及时更新

### ISSUE THREAD

**Issue by wuchjun** [Xposed-Modules-Repo/com.qingyu.mi5g#4]
双卡模式下，通知栏5g开关状态不能及时同步，而是保持上一个卡5g开关状态，需要切换后关闭通知重新打开才能同步最新状态

**Comment by buffcow** [comment]
> 双卡模式下，通知栏5g开关状态不能及时同步，而是保持上一个卡5g开关状态，需要切换后关闭通知重新打开才能同步最新状态

什么机型

**Comment by wuchjun** [comment]
> > 双卡模式下，通知栏5g开关状态不能及时同步，而是保持上一个卡5g开关状态，需要切换后关闭通知重新打开才能同步最新状态
> 
> 什么机型

小米13 MIUI14 安卓13

**Comment by buffcow** [comment]
可能修复了
