### ISSUE TITLE
1.9版本勾选电话服务后失效

### ISSUE THREAD

**Issue by HK4567** [Xposed-Modules-Repo/com.qingyu.mi5g#5]
机型：红米note9pro
版本：MIUI_12.0.11
[LSP详细日志](https://wwav.lanzoue.com/iMmtJ0nb10qh) 
![Screenshot_2023-02-12-11-47-25-994_com android shell](https://user-images.githubusercontent.com/76568542/218291940-3f615148-1123-4c21-a559-230093694cc3.jpg)

![Screenshot_2023-02-12-11-47-31-480_com android shell](https://user-images.githubusercontent.com/76568542/218291944-4f25751e-7477-43e4-b62e-68a59659e62e.jpg)

**Comment by Lovefish** [comment]
为什么要勾选那一个？感觉不需要。
