### ISSUE TITLE
更新开发版V14.0.23.3.16.DEV后显示错误

### ISSUE THREAD

**Issue by NEORUAA** [Xposed-Modules-Repo/com.qingyu.mi5g#6]
试了小米12和小米13的V14.0.23.3.16.DEV 开发版
边距出问题惹
![IMG_20230319_070201](https://user-images.githubusercontent.com/75155966/226144733-23660f91-e8d9-4b53-b4ee-3f62ee078cb1.jpg)

更新后这两个组件有变化
![Screenshot_2023-03-19-07-07-40-240_com absinthe libchecker](https://user-images.githubusercontent.com/75155966/226144719-740b3ed4-1fd5-43ae-bd38-60a677c6e9a6.png)
![Screenshot_2023-03-19-07-07-56-031_com absinthe libchecker](https://user-images.githubusercontent.com/75155966/226144722-706cf7de-d146-4f10-ba79-178b3dcefd40.png)

**Comment by kirtozz** [comment]
同小米12开发版最新，显示错误。刚想反馈的，没想到已经有了。![IMG_20230320_185123.jpg](https://user-images.githubusercontent.com/72092801/226318721-123f18e0-642a-41b5-9ba3-abd3f3ab380b.jpg)

**Comment by buffcow** [comment]
已修复
