### ISSUE TITLE
MIUIV14.0.23.3.13.DEV 开发版中UI排版出错

### ISSUE THREAD

**Issue by NyaNyaHua4290** [Xposed-Modules-Repo/com.qingyu.mi5g#7]
![Screenshot_2023-03-21-09-56-34-666_com.miui.home-edit.jpg](https://user-images.githubusercontent.com/74782007/226535871-91b69de7-017a-4526-96c9-9f602136b157.jpg)

**Comment by Lovefish** [comment]
一样，哈哈哈

**Comment by buffcow** [comment]
已修复
